---
locale: es
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Resolver una discusión.
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Determinar si un cuadro es bello.
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Empatizar con otras personas.
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Ninguno de los anteriores.
  checked: true
name: No está todo programado
