---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Español.
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Ruby.
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Mozilla Firefox.
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Python.
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Inglés.
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Javascript.
  checked: true
name: Hablándole a la computadora
