---
locale: en
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "[Notepad](https://en.wikipedia.org/wiki/Notepad)"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "[Instagram](https://www.instagram.com)"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "[Ebay](https://www.ebay.com)"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "[Airbnb](https://www.airbnb.com)"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "[Mines](https://en.wikipedia.org/wiki/Mines)"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "[Fortnite](https://www.fortnite.com)"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "[Minecraft](https://www.minecraft.net)"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "[Solitary](https://en.wikipedia.org/wiki/Solitary_Microsoft)"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "[Mumuki](https://mumuki.io/home)"
  checked: true
name: Applications vs. Systems
