---
locale: en
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: "[Notepad](https://en.wikipedia.org/wiki/Windows_Notepad)"
  checked: false
- value: "[Instagram](https://www.instagram.com)"
  checked: true
- value: "[Ebay](https://www.ebay.com)"
  checked: true
- value: "[Airbnb](https://www.airbnb.com)"
  checked: true
- value: "[Mines](https://en.wikipedia.org/wiki/Minesweeper_(video_game))"
  checked: false
- value: "[Fortnite](https://www.fortnite.com)"
  checked: true
- value: "[Minecraft](https://www.minecraft.net)"
  checked: true
- value: "[Solitaire](https://en.wikipedia.org/wiki/Microsoft_Solitaire)"
  checked: false
- value: "[Mumuki](https://mumuki.io/home)"
  checked: true
name: Applications vs. Systems
