---
locale: es
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Resolve an argument.
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Determining if a painting is beautiful.
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Empathize with other people.
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: None of the above.
  checked: true
name: Not everything is a nail
