---
locale: en
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Old mixer.
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Video game console.
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: A GPS navigation device.
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: A cell phone.
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: A wooden table.
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: An ATM.
  checked: true
name: Is this also a computer?
