---
locale: en
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: "```python\ndef double(numbr):\n  return numbr * 2\t     \n```"
  checked: false
- value: |-
    ```python
    def double(number):
      return number + number
    ```
  checked: false
- value: "```python\ndef double(number):\n  return number * 2\t    \n```"
  checked: true
- value: "```python\ndef double(number)\n  return number * 2\t    \n```"
  checked: false
name: I don't understand anything
