---
locale: en
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: Spanish.
  checked: false
- value: Ruby.
  checked: true
- value: Mozilla Firefox.
  checked: false
- value: Python.
  checked: true
- value: English.
  checked: false
- value: Javascript.
  checked: true
name: Talking to the computer
