---
locale: en
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: The accounting of a company.
  checked: true
- value: The reservation of a table in a restaurant.
  checked: true
- value: The correction of an exam.
  checked: true
- value: The development of a video game.
  checked: true
- value: Making video calls.
  checked: true
- value: Recognizing images.
  checked: true
- value: Controlling a robot on Mars.
  checked: true
name: Let's program
