---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: The accounting of a company.
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: The reservation of a table in a restaurant.
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: The correction of an exam.
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: The development of a video game.
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Making video calls.
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Recognizing images.
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Controlling a robot on Mars.
  checked: true
name: Let's program
