---
locale: en
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "```ruby\ndef greet(name)\n  \"Hello \" + name\t \nend\n```"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: |-
    ```javascript
    function greet(name) {
      return "Hello " + name;
    }
    ```
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "```python\ndef greet(name):\n  return \"Hello \" + name\t \n```"
  checked: true
name: The polyglot computer
