---
locale: en
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: "```ruby\ndef greet(name)\n  \"Hello \" + name\t         \nend\n```"
  checked: false
- value: "```javascript\nfunction greet(name) {\n  return \"Hello \" + name;    \n}\n```"
  checked: false
- value: "```python\ndef greet(name):\n  return \"Hello \" + name\t \n```"
  checked: true
name: The polyglot computer
